[tool.briefcase]
project_name = "enigmaPy"
bundle = "fr.enigmapy"
version = "0.0.1"
url = "https://enigmapy.fr"
license = "GNU General Public License v2 or later (GPLv2+)"
author = 'Geodfroy de Bouillon'
author_email = "geodfroy@enigmapy.fr"

[tool.briefcase.app.enigmapy]
formal_name = "enigmaPy"
description = "L'application du bricolage ultime"
icon = "src/enigmapy/resources/enigmapy"
sources = ['src/enigmapy']
requires = [
]


[tool.briefcase.app.enigmapy.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.enigmapy.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.enigmapy.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.enigmapy.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.enigmapy.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.enigmapy.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.enigmapy.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
